[project]
name = 'Decentralized-Automotive-History-Tracking'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.accident-reporting]
path = 'contracts/accident-reporting.clar'
clarity_version = 2
epoch = 2.5

[contracts.maintenance-log]
path = 'contracts/maintenance-log.clar'
clarity_version = 2
epoch = 2.5

[contracts.ownership-transfer]
path = 'contracts/ownership-transfer.clar'
clarity_version = 2
epoch = 2.5

[contracts.ownership-transfer_]
path = 'contracts/ownership-transfer_.clar'
clarity_version = 2
epoch = 2.5

[contracts.vehicle-registration]
path = 'contracts/vehicle-registration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
